name: Asp.Net Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Asp.Net Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore ./OntoMath-QAS/
    - name: Build
      run: dotnet build --configuration Release --no-restore ./OntoMath-QAS
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./OntoMath-QAS
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        # Optional SDK version to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 3.1.x
